convert all ipynb files to markdown, and delete the ipynb files (#4051)
* a mod's __file__ is None. (#4043)

* a mod's __file__ is None.

```
Traceback (most recent call last):
  File "./gen_doc.py", line 1270, in <module>
    set_source_code_attrs()
  File "./gen_doc.py", line 180, in set_source_code_attrs
    parse_module_file(obj)
  File "./gen_doc.py", line 234, in parse_module_file
    if os.path.splitext(src_file)[1].lower() == '.py':
  File "/usr/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

* skip the mod when its __file__ is None

* if statement wrong

* hasattr raise an expection

* convert all ipynb files to markdown, and delete the ipynb files. (#4035)

typo

Co-authored-by: Chen Long <1300851984@qq.com>